// Package restricted provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package restricted

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PageVisibility.
const (
	PageVisibilityPRIVATE PageVisibility = "PRIVATE"
	PageVisibilityPUBLIC  PageVisibility = "PUBLIC"
)

// Defines values for SpaceVisibility.
const (
	SpaceVisibilityPRIVATE SpaceVisibility = "PRIVATE"
	SpaceVisibilityPUBLIC  SpaceVisibility = "PUBLIC"
)

// CreateLinkDto defines model for CreateLinkDto.
type CreateLinkDto struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Url         *string `json:"url,omitempty"`
}

// CreatePageDto defines model for CreatePageDto.
type CreatePageDto struct {
	Description *string         `json:"description,omitempty"`
	Name        string          `json:"name"`
	Visibility  *PageVisibility `json:"visibility,omitempty"`
}

// CreateSpaceDto defines model for CreateSpaceDto.
type CreateSpaceDto struct {
	Description *string          `json:"description,omitempty"`
	Name        string           `json:"name"`
	Visibility  *SpaceVisibility `json:"visibility,omitempty"`
}

// IdInt64 defines model for IdInt64.
type IdInt64 = int64

// IdString defines model for IdString.
type IdString = string

// LinkDto defines model for LinkDto.
type LinkDto struct {
	Description *string   `json:"description,omitempty"`
	Id          *IdString `json:"id,omitempty"`
	Name        *string   `json:"name,omitempty"`
	PageId      *IdString `json:"pageId,omitempty"`
	Url         *string   `json:"url,omitempty"`
}

// PageDto defines model for PageDto.
type PageDto struct {
	Description *string         `json:"description,omitempty"`
	Icon        *string         `json:"icon,omitempty"`
	Id          *IdString       `json:"id,omitempty"`
	Name        *string         `json:"name,omitempty"`
	OwnerId     *IdInt64        `json:"ownerId,omitempty"`
	SpaceId     *IdString       `json:"spaceId,omitempty"`
	Visibility  *PageVisibility `json:"visibility,omitempty"`
}

// PageVisibility defines model for PageVisibility.
type PageVisibility string

// SpaceDto defines model for SpaceDto.
type SpaceDto struct {
	Description *string          `json:"description,omitempty"`
	Id          *IdString        `json:"id,omitempty"`
	Name        *string          `json:"name,omitempty"`
	OwnerId     *IdInt64         `json:"ownerId,omitempty"`
	Visibility  *SpaceVisibility `json:"visibility,omitempty"`
}

// SpaceVisibility defines model for SpaceVisibility.
type SpaceVisibility string

// UpdateLinkJSONRequestBody defines body for UpdateLink for application/json ContentType.
type UpdateLinkJSONRequestBody = CreateLinkDto

// UpdatePageJSONRequestBody defines body for UpdatePage for application/json ContentType.
type UpdatePageJSONRequestBody = CreatePageDto

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody = CreateLinkDto

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceDto

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = CreateSpaceDto

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = CreatePageDto

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete a link
	// (DELETE /v1/links/{linkId})
	DeleteLink(ctx echo.Context, linkId IdString) error
	// Get a link
	// (GET /v1/links/{linkId})
	GetLink(ctx echo.Context, linkId IdString) error
	// Update a link
	// (PATCH /v1/links/{linkId})
	UpdateLink(ctx echo.Context, linkId IdString) error
	// Delete a page
	// (DELETE /v1/pages/{pageId})
	DeletePage(ctx echo.Context, pageId IdString) error
	// Get a page
	// (GET /v1/pages/{pageId})
	GetPage(ctx echo.Context, pageId IdString) error
	// Update a page
	// (PATCH /v1/pages/{pageId})
	UpdatePage(ctx echo.Context, pageId IdString) error
	// List links of a page
	// (GET /v1/pages/{pageId}/links)
	GetLinks(ctx echo.Context, pageId IdString) error
	// Create a link
	// (POST /v1/pages/{pageId}/links)
	CreateLink(ctx echo.Context, pageId IdString) error
	// List all spaces
	// (GET /v1/spaces)
	GetSpaces(ctx echo.Context) error
	// Create a space
	// (POST /v1/spaces)
	CreateSpace(ctx echo.Context) error
	// Delete a space
	// (DELETE /v1/spaces/{spaceId})
	DeleteSpace(ctx echo.Context, spaceId IdString) error
	// Get a space
	// (GET /v1/spaces/{spaceId})
	GetSpace(ctx echo.Context, spaceId IdString) error
	// Update a space
	// (PATCH /v1/spaces/{spaceId})
	UpdateSpace(ctx echo.Context, spaceId IdString) error
	// List pages of a space
	// (GET /v1/spaces/{spaceId}/pages)
	GetPages(ctx echo.Context, spaceId IdString) error
	// Create a page
	// (POST /v1/spaces/{spaceId}/pages)
	CreatePage(ctx echo.Context, spaceId IdString) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteLink converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "linkId" -------------
	var linkId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "linkId", runtime.ParamLocationPath, ctx.Param("linkId"), &linkId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter linkId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteLink(ctx, linkId)
	return err
}

// GetLink converts echo context to params.
func (w *ServerInterfaceWrapper) GetLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "linkId" -------------
	var linkId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "linkId", runtime.ParamLocationPath, ctx.Param("linkId"), &linkId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter linkId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetLink(ctx, linkId)
	return err
}

// UpdateLink converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "linkId" -------------
	var linkId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "linkId", runtime.ParamLocationPath, ctx.Param("linkId"), &linkId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter linkId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateLink(ctx, linkId)
	return err
}

// DeletePage converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pageId" -------------
	var pageId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "pageId", runtime.ParamLocationPath, ctx.Param("pageId"), &pageId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletePage(ctx, pageId)
	return err
}

// GetPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetPage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pageId" -------------
	var pageId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "pageId", runtime.ParamLocationPath, ctx.Param("pageId"), &pageId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPage(ctx, pageId)
	return err
}

// UpdatePage converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pageId" -------------
	var pageId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "pageId", runtime.ParamLocationPath, ctx.Param("pageId"), &pageId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatePage(ctx, pageId)
	return err
}

// GetLinks converts echo context to params.
func (w *ServerInterfaceWrapper) GetLinks(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pageId" -------------
	var pageId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "pageId", runtime.ParamLocationPath, ctx.Param("pageId"), &pageId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetLinks(ctx, pageId)
	return err
}

// CreateLink converts echo context to params.
func (w *ServerInterfaceWrapper) CreateLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pageId" -------------
	var pageId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "pageId", runtime.ParamLocationPath, ctx.Param("pageId"), &pageId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateLink(ctx, pageId)
	return err
}

// GetSpaces converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpaces(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSpaces(ctx)
	return err
}

// CreateSpace converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSpace(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateSpace(ctx)
	return err
}

// DeleteSpace converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSpace(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spaceId" -------------
	var spaceId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "spaceId", runtime.ParamLocationPath, ctx.Param("spaceId"), &spaceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spaceId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteSpace(ctx, spaceId)
	return err
}

// GetSpace converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpace(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spaceId" -------------
	var spaceId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "spaceId", runtime.ParamLocationPath, ctx.Param("spaceId"), &spaceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spaceId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSpace(ctx, spaceId)
	return err
}

// UpdateSpace converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSpace(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spaceId" -------------
	var spaceId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "spaceId", runtime.ParamLocationPath, ctx.Param("spaceId"), &spaceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spaceId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateSpace(ctx, spaceId)
	return err
}

// GetPages converts echo context to params.
func (w *ServerInterfaceWrapper) GetPages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spaceId" -------------
	var spaceId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "spaceId", runtime.ParamLocationPath, ctx.Param("spaceId"), &spaceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spaceId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPages(ctx, spaceId)
	return err
}

// CreatePage converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "spaceId" -------------
	var spaceId IdString

	err = runtime.BindStyledParameterWithLocation("simple", false, "spaceId", runtime.ParamLocationPath, ctx.Param("spaceId"), &spaceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spaceId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreatePage(ctx, spaceId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/v1/links/:linkId", wrapper.DeleteLink)
	router.GET(baseURL+"/v1/links/:linkId", wrapper.GetLink)
	router.PATCH(baseURL+"/v1/links/:linkId", wrapper.UpdateLink)
	router.DELETE(baseURL+"/v1/pages/:pageId", wrapper.DeletePage)
	router.GET(baseURL+"/v1/pages/:pageId", wrapper.GetPage)
	router.PATCH(baseURL+"/v1/pages/:pageId", wrapper.UpdatePage)
	router.GET(baseURL+"/v1/pages/:pageId/links", wrapper.GetLinks)
	router.POST(baseURL+"/v1/pages/:pageId/links", wrapper.CreateLink)
	router.GET(baseURL+"/v1/spaces", wrapper.GetSpaces)
	router.POST(baseURL+"/v1/spaces", wrapper.CreateSpace)
	router.DELETE(baseURL+"/v1/spaces/:spaceId", wrapper.DeleteSpace)
	router.GET(baseURL+"/v1/spaces/:spaceId", wrapper.GetSpace)
	router.PATCH(baseURL+"/v1/spaces/:spaceId", wrapper.UpdateSpace)
	router.GET(baseURL+"/v1/spaces/:spaceId/pages", wrapper.GetPages)
	router.POST(baseURL+"/v1/spaces/:spaceId/pages", wrapper.CreatePage)

}
