// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package sqlc

import (
	"context"
)

const findBookmarkById = `-- name: FindBookmarkById :one
SELECT id, page_id, name, description, url, created_at, updated_at
FROM bookmarks b
WHERE id = ? LIMIT 1
`

func (q *Queries) FindBookmarkById(ctx context.Context, id int64) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, findBookmarkById, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
