// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Space struct {
	ID          int64      `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	Description *string    `db:"description" json:"description"`
	Visibility  string     `db:"visibility" json:"visibility"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
}

type SpacesUser struct {
	SpaceID   int64      `db:"space_id" json:"space_id"`
	UserID    int64      `db:"user_id" json:"user_id"`
	Role      string     `db:"role" json:"role"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID          int64      `db:"id" json:"id"`
	Email       string     `db:"email" json:"email"`
	Username    string     `db:"username" json:"username"`
	Password    string     `db:"password" json:"-"`
	DisplayName *string    `db:"display_name" json:"display_name"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
}
