// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Bookmark struct {
	ID          int64       `db:"id" json:"id"`
	PageID      int64       `db:"page_id" json:"page_id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	Url         interface{} `db:"url" json:"url"`
	CreatedAt   *time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time  `db:"updated_at" json:"updated_at"`
}

type Page struct {
	ID          int64      `db:"id" json:"id"`
	SpaceID     int64      `db:"space_id" json:"space_id"`
	Name        string     `db:"name" json:"name"`
	Description *string    `db:"description" json:"description"`
	Visibility  string     `db:"visibility" json:"visibility"`
	ParentID    *int64     `db:"parent_id" json:"parent_id"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
}

type Space struct {
	ID          int64      `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	Description *string    `db:"description" json:"description"`
	Visibility  string     `db:"visibility" json:"visibility"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
}

type SpacesUser struct {
	SpaceID   int64      `db:"space_id" json:"space_id"`
	UserID    int64      `db:"user_id" json:"user_id"`
	Role      string     `db:"role" json:"role"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID          int64      `db:"id" json:"id"`
	Email       string     `db:"email" json:"email"`
	Username    string     `db:"username" json:"username"`
	Password    string     `db:"password" json:"-"`
	DisplayName *string    `db:"display_name" json:"display_name"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
}
