### GET request to example server
POST {{host}}/auth/refresh
Content-Type: application/json
Cookie: refreshToken={{refreshToken}}

> {%
    client.global.set("accessToken", response.body.accessToken);
    const cookieString = response.headers.valuesOf("Set-Cookie")[0]
    if (cookieString && cookieString.includes("=")) {
        client.global.set("refreshToken", cookieString.split(";")[0].split("=")[1]);
    }
%}

###