### GET request to example server
POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "username": "{{username}}"
}

### GET create user random
< {%
    const min = 1;
    const max = 99999;
    const rnd = Math.floor(Math.random() * (max - min + 1)) + min;
    request.variables.set("random", rnd);
%}

POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "{{random}}-{{email}}",
  "password": "{{password}}",
  "username": "{{username}}-{{random}}",
  "displayName": "{{random}}-{{username}}"
}

### GET request to example server
POST {{host}}/auth/login
Content-Type: application/json

{
  "user": "danny-97894",
  "password": "{{password}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    const cookieString = response.headers.valuesOf("Set-Cookie")[0]
    if (cookieString && cookieString.includes("=")) {
        client.global.set("refreshToken", cookieString.split(";")[0].split("=")[1]);
    }
%}


### GET create user random Bad Request
< {%
    const min = 1;
    const max = 99999;
    const rnd = Math.floor(Math.random() * (max - min + 1)) + min;
    request.variables.set("random", rnd);%}

POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "{{email}}-{{random}}",
  "password": "",
  "username": "{{username}}-{{random}}"
}