// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID        int64        `db:"id" json:"id"`
	Email     string       `db:"email" json:"email"`
	Username  string       `db:"username" json:"username"`
	Password  string       `db:"password" json:"password"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}
