// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: spaces.sql

package sqlc

import (
	"context"
)

const findSpaceById = `-- name: FindSpaceById :one
SELECT id, name, description, owner_id, visibility, created_at, updated_at
FROM spaces u
WHERE id = ? LIMIT 1
`

func (q *Queries) FindSpaceById(ctx context.Context, id int64) (Space, error) {
	row := q.db.QueryRowContext(ctx, findSpaceById, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
