// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Role struct {
	ID          int64          `db:"id"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
	Name        string         `db:"name"`
	Description sql.NullString `db:"description"`
}

type User struct {
	ID                    int64          `db:"id"`
	CreatedAt             sql.NullTime   `db:"created_at"`
	UpdatedAt             sql.NullTime   `db:"updated_at"`
	DeletedAt             sql.NullTime   `db:"deleted_at"`
	Username              string         `db:"username"`
	Password              string         `db:"password"`
	Email                 string         `db:"email"`
	FirstName             sql.NullString `db:"first_name"`
	LastName              sql.NullString `db:"last_name"`
	Active                bool           `db:"active"`
	ActivationConfirmedAt sql.NullTime   `db:"activation_confirmed_at"`
}

type UsersRole struct {
	UserID    int64        `db:"user_id"`
	RoleID    int64        `db:"role_id"`
	CreatedAt sql.NullTime `db:"created_at"`
}
