package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/Serbroda/ragbag/cmd/graphql-server/graph/generated"
	"github.com/Serbroda/ragbag/pkg/model"
)

// CreateSpace is the resolver for the createSpace field.
func (r *myMutationResolver) CreateSpace(ctx context.Context, space model.CreateSpace) (*model.Space, error) {
	panic(fmt.Errorf("not implemented: CreateSpace - createSpace"))
}

// Space is the resolver for the space field.
func (r *myQueryResolver) Space(ctx context.Context, id string) (*model.Space, error) {
	panic(fmt.Errorf("not implemented: Space - space"))
}

// Spaces is the resolver for the spaces field.
func (r *myQueryResolver) Spaces(ctx context.Context) ([]*model.Space, error) {
	panic(fmt.Errorf("not implemented: Spaces - spaces"))
}

// ID is the resolver for the id field.
func (r *spaceResolver) ID(ctx context.Context, obj *model.Space) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// MyMutation returns generated.MyMutationResolver implementation.
func (r *Resolver) MyMutation() generated.MyMutationResolver { return &myMutationResolver{r} }

// MyQuery returns generated.MyQueryResolver implementation.
func (r *Resolver) MyQuery() generated.MyQueryResolver { return &myQueryResolver{r} }

// Space returns generated.SpaceResolver implementation.
func (r *Resolver) Space() generated.SpaceResolver { return &spaceResolver{r} }

type myMutationResolver struct{ *Resolver }
type myQueryResolver struct{ *Resolver }
type spaceResolver struct{ *Resolver }
