### GET request to example server
POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "{{user}}-2",
  "fullName": "Max Mustermann-2",
  "password": "{{password}}"
}

### Login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{user}}-2",
  "password": "{{password}}"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

###