@SPACE_ID = 2
@ACCOUNT_ID = 3
@ACCOUNT_ROLE = CONTRIBUTOR

### GET request to example server
PUT {{host}}/api/v1/spaces/{{SPACE_ID}}/accounts/add
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "accountId": {{ACCOUNT_ID}},
  "role": "{{ACCOUNT_ROLE}}"
}

###