// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type ActivationToken struct {
	UserID    int64        `db:"user_id"`
	TokenHash string       `db:"token_hash"`
	ExpiresAt sql.NullTime `db:"expires_at"`
	CreatedAt sql.NullTime `db:"created_at"`
}

type Link struct {
	ID          int64          `db:"id"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
	ShortID     sql.NullString `db:"short_id"`
	PageID      int64          `db:"page_id"`
	Name        sql.NullString `db:"name"`
	Url         string         `db:"url"`
	Description sql.NullString `db:"description"`
}

type Page struct {
	ID          int64          `db:"id"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
	ShortID     string         `db:"short_id"`
	OwnerID     int64          `db:"owner_id"`
	SpaceID     int64          `db:"space_id"`
	ParentID    sql.NullInt64  `db:"parent_id"`
	Name        string         `db:"name"`
	Description sql.NullString `db:"description"`
	Visibility  string         `db:"visibility"`
}

type PasswordResetToken struct {
	UserID    int64        `db:"user_id"`
	TokenHash string       `db:"token_hash"`
	ExpiresAt time.Time    `db:"expires_at"`
	CreatedAt sql.NullTime `db:"created_at"`
}

type Role struct {
	ID          int64          `db:"id"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
	Name        string         `db:"name"`
	Description sql.NullString `db:"description"`
}

type Space struct {
	ID          int64          `db:"id"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
	ShortID     string         `db:"short_id"`
	OwnerID     int64          `db:"owner_id"`
	Name        string         `db:"name"`
	Description sql.NullString `db:"description"`
	Visibility  string         `db:"visibility"`
}

type User struct {
	ID                    int64        `db:"id"`
	CreatedAt             sql.NullTime `db:"created_at"`
	UpdatedAt             sql.NullTime `db:"updated_at"`
	DeletedAt             sql.NullTime `db:"deleted_at"`
	FirstName             string       `db:"first_name"`
	LastName              string       `db:"last_name"`
	Username              string       `db:"username"`
	Password              string       `db:"password"`
	Email                 string       `db:"email"`
	Active                bool         `db:"active"`
	ActivationConfirmedAt sql.NullTime `db:"activation_confirmed_at"`
}

type UsersRole struct {
	UserID    int64        `db:"user_id"`
	RoleID    int64        `db:"role_id"`
	CreatedAt sql.NullTime `db:"created_at"`
}

type UsersSpace struct {
	UserID    int64        `db:"user_id"`
	SpaceID   int64        `db:"space_id"`
	RoleID    int64        `db:"role_id"`
	CreatedAt sql.NullTime `db:"created_at"`
}
