name: Build

on:
  push:
    branches:
      - "**"
      - "!master"
      - "!develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: docker-practice/actions-setup-docker@master
      - run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      - run: make build
