name: Pre Release

on:
  push:
    branches:
      - "develop"

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: docker-practice/actions-setup-docker@master
      - run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      - run: jq -r '"BUILD_VERSION=\(.version)"' pipeconf.json | sed "s/$/+$(date '+%s')/"  >> $GITHUB_ENV
      - run: make build BINARY_VERSION="${{ env.BUILD_VERSION }}"
      - run: echo "${{ env.BUILD_VERSION }}"
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: "refs/tags/${{ env.BUILD_VERSION }}",
      #         sha: context.sha
      #       })
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "next"
          prerelease: true
          title: "${{ env.BUILD_VERSION }}"
          files: |
            build/**
