name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: jq -r '"BUILD_VERSION=\(.version)"' pipeconf.json >> $GITHUB_ENV
      - run: make build BINARY_VERSION="${{ env.BUILD_VERSION }}"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.BUILD_VERSION }}",
              sha: context.sha
            })
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "${{ env.BUILD_VERSION }}"
          files: |
            build/**
